version: "3.7"
services:
  hubot:
    container_name: hubot
    image: hubot
    build:
      context: .
      args:
        - HUBOT_ADAPTER=shell
        - HUBOT_DESCRIPTION=Delightfully aware robutt
        - HUBOT_NAME=Hubot
        - HUBOT_OWNER=Bot Wrangler <bw@example.com>
        - HUBOT_PORT=8080
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "8080:8080"
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    env_file:
      - hubot.env
    depends_on:
      - redis
    links:
      - redis
    tty: true
  redis:
    container_name: redis
    image: redis:buster
    command: redis-server --appendonly yes
    volumes:
      - hubot-brain:/data
volumes:
  hubot-brain:
    name: hubot-brain
